---
- name: Get MySQL version.
  command: 'mysql --version'
  register: mysql_cli_version
  changed_when: false

- name: Acquire temporary root password
  shell: awk '$0 ~ "temporary password" {print $11}' {{ mysql_log_error }}
  register: mysql_root_temp_password_shell
  when: ((mysql_install_packages | bool) or mysql_root_password_update) and ('5.7.' in mysql_cli_version.stdout)

- name: Set temporary root password
  set_fact:
    mysql_root_temp_password: "{{ mysql_root_temp_password_shell.stdout }}"
  when: mysql_root_temp_password_shell is not skipped and mysql_root_temp_password_shell.stdout | length > 0

- name: Copy .my.cnf file with temporary root password credentials
  template:
      src: "root-temporary-my.cnf.j2"
      dest: "{{ mysql_root_home }}/.my.cnf"
      owner: "{{ mysql_root_username }}"
      mode: 0600
  when: mysql_root_temp_password is defined

- name: Test temporary root password expired
  shell: "mysql -NBe 'SELECT NOW();'"
  register: mysql_temp_password_test_result
  when: mysql_root_temp_password is defined
  changed_when: false
  failed_when: false

- name: Update MySQL root password for localhost root account (5.7.x)
  no_log: true
  shell: >
      mysql -NBe 'ALTER USER "{{ mysql_root_username }}"@"localhost" IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_password }}";'
      --connect-expired-password
  when: mysql_root_temp_password is defined and 'connect-expired-password' in mysql_temp_password_test_result.stdout

- name: Overwrite .my.cnf file with root password credentials
  template:
    src: "root-my.cnf.j2"
    dest: "{{ mysql_root_home }}/.my.cnf"
    owner: "{{ mysql_root_username }}"
    mode: 0600
  when: mysql_root_temp_password is defined
