FROM ubuntu:16.04
RUN apt-get update

# Install Ansible
RUN apt -y install libffi-dev libssl-dev python-setuptools python-dev python-pip
RUN pip install ansible
RUN mkdir -p /etc/ansible

# TODO: Switch to official apt repo after the following issue is resolved:
# https://github.com/ansible/ansible/issues/15524

# Install Ansible
#RUN apt-get install -y software-properties-common git
#RUN apt-add-repository -y ppa:ansible/ansible
#RUN apt-get update
#RUN apt-get install -y ansible

COPY initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
