name: Ansible

on: [push]
env:
  ROLE_NAME: mysql

jobs:
  molecule:
    name: Molecule

    runs-on: ubuntu-latest

    strategy:
      matrix:
        MOLECULE_DISTRO:
          - centos7
          - centos6
          - ubuntu1804
          - ubuntu1604
          - debian10

    steps:
    - uses: actions/checkout@v1

    # Using Python 3.6 to match travis-ci default. 
    # See https://docs.travis-ci.com/user/languages/python/#specifying-python-versions
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    
    - name: Install Ansible & Molecule
      run: |
        pip install molecule docker
        ansible --version
        molecule --version

    - name: Test with Molecule
      run: |
        cd ..
        mv ansible-role-$ROLE_NAME geerlingguy.$ROLE_NAME
        cd geerlingguy.$ROLE_NAME
        molecule test
